# Generated by Django 5.2.6 on 2025-09-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('model', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('produce_date', models.IntegerField()),
            ],
        ),
    ]
